version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running training on SageMaker..."
      - python scripts/train.py

artifacts:
  files:
    - models/**

